### ISSUE TITLE
Husky disallows using another package manager than npm

### ISSUE THREAD

**Issue by ioayoub** [WildCodeSchool/create-js-monorepo#84]
❌ Problem : If you try to use another package manager than npm (pnpm/yarn/...) the new rules of husky generate an error and blocks the current commit.

⚡️ Potential fix : Add rule to ignore pnpm-lock.yaml, yarn-lock and maybe package-lock.json

**Comment by rocambille** [comment]
Arf... nice catch :slightly_smiling_face: 

The purpose of the new rules is to prevent package installation in the root directory. We can ignore `package.json` since now it looks legit to change it. But we can't ignore lock files to keep the rule doing its job. If I'm not mistaken, the config variables of `package.json` have no impact in lock files. So the fix would be:

1. Update `.husky/pre-commit` as follow:

```
fileList=$(git diff --cached --name-only :^package.json :^README.md :^frontend :^backend)
```
2. Add lock files for yarn and pnpm in the template (and commit them with the secret `-n` option to make no verifications on this single commit): in fact, they should have been there from the start.

What do you think? Can you try a PR? :slightly_smiling_face:

**Comment by ioayoub** [comment]
Sure! I'll work on this next week 😉
